# Generated by Django 5.0 on 2023-12-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
