# Generated by Django 5.0 on 2023-12-09 20:40

from django.db import migrations


def populate_status(apps, schema_editor):
    entries = {
        'to do': 'New',
        'in progress': 'In Progress',
        'done': 'Done',
    }

    Status = apps.get_model('issues', 'Status')
    for key, value in entries.items():
        Status_obj = Status(name=key, description=value)
        Status_obj.save()


class Migration(migrations.Migration):
    
        dependencies = [
            ('issues', '0002_status_description'),
        ]
    
        operations = [
            migrations.RunPython(populate_status),
        ]