# Generated by Django 5.0 on 2023-12-09 20:42

from django.db import migrations




def populate_team(apps, schema_editor):
    entries = {
        'team1': 'team1',
        'team2': 'team2',
        'team3': 'team3',
    }

    Team = apps.get_model('accounts', 'Team')
    for key, value in entries.items():
        Team_obj = Team(name=key, description=value)
        Team_obj.save()
def populate_roles(apps, schema_editor):
    entries = {
        'developer': 'admin',
        'scrum master': 'developer',
        'product owner': 'tester',
    }

    Role = apps.get_model('accounts', 'Role')
    for key, value in entries.items():
        Role_obj = Role(name=key, description=value)
        Role_obj.save()

class Migration(migrations.Migration):
    
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_team),
        migrations.RunPython(populate_roles),
    ]
